#variables:
#  CI_DEBUG_TRACE: "true"
variables:
  GITLAB_TOKEN: $GITLAB_TOKEN
  GITLAB_FQDN: $GITLAB_FQDN
  ZBX_USER: $ZBX_USER
  ZBX_PASSWORD: $ZBX_PASSWORD

.review: &review
  image: python:3.4
  script:
    - set
    - git config --global user.email "you@example.com"
    - git config --global user.name "Zabbix Auto Backup"
    - git clone https://oauth2:$GITLAB_TOKEN@$GITLAB_FQDN/$GROUP/$PROJECT.git
    - make ZBX_URL=$ZBX_URL ZBX_USER=$ZBX_USER ZBX_PASSWORD=$ZBX_PASSWORD TARGET_DIR=./$PROJECT SAVE_YAML=$SAVE_YAML

.review-manual: &review-manual
  <<: *review
  when: manual

.review-schedules: &review-schedules
  <<: *review
  only:
    - schedules

YAML devops-zabbix:
  variables:
    PROJECT: devops-zabbix-yaml
    GROUP: scm
    ZBX_URL: $DEVOPS_ZBX_URL
    SAVE_YAML: --save-yaml
  <<: *review-manual

YAML SCHEDULE devops-zabbix:
  variables:
    PROJECT: devops-zabbix-yaml
    GROUP: scm
    ZBX_URL: $DEVOPS_ZBX_URL
    SAVE_YAML: --save-yaml
  <<: *review-schedules

XML SCHEDULE devops-zabbix:
  variables:
    PROJECT: devops-zabbix-xml
    GROUP: scm
    ZBX_URL: $DEVOPS_ZBX_URL
  <<: *review-schedules

XML SCHEDULE qa-zabbix:
  variables:
    PROJECT: qa-zabbix-xml
    GROUP: scm
    ZBX_URL: $QA_ZBX_URL
  <<: *review-schedules

