#variables:
#  CI_DEBUG_TRACE: "true"
variables:
  GITLAB_TOKEN: $GITLAB_TOKEN
  GITLAB_FQDN: $GITLAB_FQDN
  ZBX_USER: $ZBX_USER
  ZBX_PASSWORD: $ZBX_PASSWORD

.review: &review
  image: python:3.4
  script:
    - set
    - git clone https://oauth2:$GITLAB_TOKEN@$GITLAB_FQDN/$GROUP/$PROJECT.git
    - make backup ZBX_URL=$ZBX_URL ZBX_USER=$ZBX_USER ZBX_PASSWORD='${ZBX_PASSWORD}' TARGET_DIR=./$PROJECTNAME
  only:
    - master

devops-zabbix:
  variables:
    PROJECT: devops-zabbix-xml
    GROUP: scm
    ZBX_URL: $DEVOPS_ZBX_URL
  <<: *review

#qa-zabbix:
#  <<: *review

