variables:
#  CI_DEBUG_TRACE: "true"
  GITLAB_TOKEN: $GITLAB_TOKEN # https://docs.gitlab.com/ce/user/profile/personal_access_tokens.html
  GITLAB_FQDN: $GITLAB_FQDN # You instanse FQDN, e.g. https://gitlab.com or https://gitlab.example.com
  ZABBIX_USERNAME: $ZBX_USER # Zabbix user with admin privilege
  ZABBIX_PASSWORD: $ZBX_PASSWORD
  GITLAB_GROUP: $GITLAB_GROUP
  OLD_ZABBIX_URL: $OLD_ZABBIX_URL
  NEW_ZABBIX_URL: $NEW_ZABBIX_URL
  NEW_YAML_REPO: $NEW_YAML_REPO
  NEW_XML_REPO: $NEW_XML_REPO
  OLD_YAML_REPO: $OLD_YAML_REPO
  OLD_XML_REPO: $OLD_XML_REPO
  USER_EMAIL: $USER_EMAIL
  USER_NAME: $USER_NAME

before_script:
  - date
  - python -m pip install --user -r requirements.txt

after_script:
  - date

.review: &review
  tags:
    - dind
  image: python:3
  script:
    - git config --global user.email "$USER_EMAIL"
    - git config --global user.name "$USER_NAME"
    - git clone https://oauth2:$GITLAB_TOKEN@$GITLAB_FQDN/$GITLAB_GROUP/$GITLAB_REPO.git
    - cd $GITLAB_REPO
    - git checkout -b develop origin/develop || git checkout develop
    - git pull
    - rm -rf *
    - python ../zabbix-export.py $SAVE_YAML
    - git add .
    - d=$(date +%Y-%m-%d)
    - "git commit -m':robot: Autobackup' ||:"
    - git push origin develop


.review-manual: &review-manual
  <<: *review
  when: manual

.review-schedules: &review-schedules
  <<: *review
  only:
    - schedules

#
# You job for review and backup
#
# Example for you instance
YAML new zabbix:
 variables:
   GITLAB_REPO: $NEW_YAML_REPO
   ZABBIX_URL: $NEW_ZABBIX_URL
   SAVE_YAML: --save-yaml
 <<: *review-manual

YAML SCHEDULE new zabbix:
 variables:
   GITLAB_REPO: $NEW_YAML_REPO
   ZABBIX_URL: $NEW_ZABBIX_URL
   SAVE_YAML: --save-yaml
 <<: *review-schedules

XML new zabbix:
 variables:
   GITLAB_REPO: $NEW_XML_REPO
   ZABBIX_URL: $NEW_ZABBIX_URL
   SAVE_YAML: ""
 <<: *review-manual

# XML SCHEDULE new zabbix:
#  variables:
#    GITLAB_REPO: $NEW_XML_REPO
#    ZABBIX_URL: $NEW_ZABBIX_URL
#    SAVE_YAML: ""
#  <<: *review-schedules

YAML old zabbix:
 variables:
   GITLAB_REPO: $OLD_YAML_REPO
   ZABBIX_URL: $OLD_ZABBIX_URL
   SAVE_YAML: --save-yaml
 <<: *review-manual

YAML SCHEDULE old zabbix:
 variables:
   GITLAB_REPO: $OLD_YAML_REPO
   ZABBIX_URL: $OLD_ZABBIX_URL
   SAVE_YAML: --save-yaml
 <<: *review-schedules

XML old zabbix:
 variables:
   GITLAB_REPO: $OLD_XML_REPO
   ZABBIX_URL: $OLD_ZABBIX_URL
   SAVE_YAML: ""
 <<: *review-manual

# XML SCHEDULE old zabbix:
#  variables:
#    GITLAB_REPO: $OLD_XML_REPO
#    ZABBIX_URL: $OLD_ZABBIX_URL
#    SAVE_YAML: ""
#  <<: *review-schedules
