variables:
#  CI_DEBUG_TRACE: "true"
  GITLAB_TOKEN: $GITLAB_TOKEN # https://docs.gitlab.com/ce/user/profile/personal_access_tokens.html
  GITLAB_FQDN: gitlab.southbridge.ru # You instanse FQDN, e.g. https://gitlab.com or https://gitlab.example.com
  ZBX_USER: $ZBX_USER # Zabbix user with admin privilege
  ZBX_PASSWORD: $ZBX_PASSWORD

before_script:
  - apt-get update && apt-get -y dist-updrade && apt-get -y install python3.6-minimal git
  - python3 -mpip install --user -r requirements.txt

.review: &review
  image: ubuntu:18.04
  script:
    - git config --global user.email "e.tereshkov@southbridge.ru"
    - git config --global user.name "Zabbix Auto Backup"
    - git clone https://oauth2:$GITLAB_TOKEN@$GITLAB_FQDN/$GITLAB_GROUP/$GITLAB_REPO.git
    - cd $GITLAB_REPO
    - git checkout -b develop origin/develop || git checkout develop
    - git pull
    - rm -vrf *
    - python3 ../zabbix-export.py --zabbix-url $ZBX_URL --zabbix-username $ZBX_USER --zabbix-password $ZBX_PASSWORD $SAVE_YAML
    - git add .
    - d=$(date +%Y-%m-%d)
    - "git commit -m':robot: Autobackup'"
    - git push origin develop


.review-manual: &review-manual
  <<: *review
  when: manual

.review-schedules: &review-schedules
  <<: *review
  only:
    - schedules

#
# You job for review and backup
#
# Example for you instance
YAML zabbix4.2:
 variables:
   GITLAB_REPO: zabbix42-yaml
   GITLAB_GROUP: e.tereshkov
   ZBX_URL: https://zabbix42.southbridge.io
   SAVE_YAML: --save-yaml
 <<: *review-manual

YAML SCHEDULE zabbix4.2:
 variables:
   GITLAB_REPO: zabbix42-yaml
   GITLAB_GROUP: e.tereshkov
   ZBX_URL: https://zabbix42.southbridge.io
   SAVE_YAML: --save-yaml
 <<: *review-schedules
