#variables:
#  CI_DEBUG_TRACE: "true"
variables:
  GITLAB_TOKEN: $GITLAB_TOKEN

.review: &review
  image: python:3.4
  script:
    - git clone https://oauth2:GITLAB_TOKEN@$GITLAB_URL/$GROUP/$PROJECT.git
    - make backup ZBX_URL=$ZBX_URL ZBX_USER=$ZBX_USER ZBX_PASSWORD='$ZBX_PASSWORD' TARGET_DIR=./$PROJECTNAME
  only:
    - master

devops-zabbix:
  variables:
    PROJECT: devops-zabbix-xml
    GROUP: scm
    ZBX_URL: $DEVOPS_ZBX_URL
    ZBX_USER: $DEVOPS_ZBX_USER
    ZBX_PASSWORD: $DEVOPS_ZBX_PASSWORD
  <<: *review

#qa-zabbix:
#  <<: *review

