variables:
#  CI_DEBUG_TRACE: "true"
  GITLAB_TOKEN: $GITLAB_TOKEN
  GITLAB_FQDN: $GITLAB_FQDN
  ZBX_USER: $ZBX_USER
  ZBX_PASSWORD: $ZBX_PASSWORD

before_script:
  - python -mpip install -r requirements.txt

.review: &review
  image: python:3.4
  script:
    - git config --global user.email "you@example.com"
    - git config --global user.name "Zabbix Auto Backup"
    - git clone https://oauth2:$GITLAB_TOKEN@$GITLAB_FQDN/$GROUP/$PROJECT.git
    - cd $PROJECT
    - git checkout -b develop origin/develop || git checkout develop
    - git pull
    - rm -vrf *
    - python ../zabbix-export.py --zabbix-url $ZBX_URL --zabbix-username $ZBX_USER --zabbix-password '$ZBX_PASSWORD' $SAVE_YAML
    - git add .
    - d=$(date +%Y-%m-%d)
    - "git commit -m':robot: Autobackup ${d}"
    - git push origin develop


.review-manual: &review-manual
  <<: *review
  when: manual

.review-schedules: &review-schedules
  <<: *review
  only:
    - schedules

YAML devops-zabbix:
  variables:
    PROJECT: devops-zabbix-yaml
    GROUP: scm
    ZBX_URL: $DEVOPS_ZBX_URL
    SAVE_YAML: --save-yaml
  <<: *review-manual

YAML SCHEDULE devops-zabbix:
  variables:
    PROJECT: devops-zabbix-yaml
    GROUP: scm
    ZBX_URL: $DEVOPS_ZBX_URL
    SAVE_YAML: --save-yaml
  <<: *review-schedules

XML SCHEDULE devops-zabbix:
  variables:
    PROJECT: devops-zabbix-xml
    GROUP: scm
    ZBX_URL: $DEVOPS_ZBX_URL
  <<: *review-schedules

XML SCHEDULE qa-zabbix:
  variables:
    PROJECT: qa-zabbix-xml
    GROUP: scm
    ZBX_URL: $QA_ZBX_URL
  <<: *review-schedules

