# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3
repos:
- repo: local
  hooks:
    - id: generate-requirements
      name: Generate requirements
      entry: poetry export --without-hashes -f requirements.txt -o requirements.txt
      language: system
      types: [python]
      pass_filenames: false

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-ast
  - id: fix-encoding-pragma

- repo: https://github.com/psf/black
  rev: 24.2.0
  hooks:
    - id: black
      name: black
      entry: black
      types: [python]

- repo: https://github.com/myint/autoflake
  rev: v2.3.0
  hooks:
  - id: autoflake
    name: autoflake
    entry: autoflake
    language: python
    types: [python]
    args: [--in-place, --remove-all-unused-imports, --remove-duplicate-keys]

- repo: https://github.com/PyCQA/flake8
  rev: 7.0.0
  hooks:
  - id: flake8
